from _typeshed import Incomplete
from pandas.plotting._matplotlib import AreaPlot as PandasAreaPlot, BarPlot as PandasBarPlot, BarhPlot as PandasBarhPlot, BoxPlot as PandasBoxPlot, HistPlot as PandasHistPlot, KdePlot as PandasKdePlot, LinePlot as PandasLinePlot, PiePlot as PandasPiePlot, ScatterPlot as PandasScatterPlot
from pyspark.pandas.plot import BoxPlotBase as BoxPlotBase, HistogramPlotBase as HistogramPlotBase, KdePlotBase as KdePlotBase, SampledPlotBase as SampledPlotBase, TopNPlotBase as TopNPlotBase, unsupported_function as unsupported_function

class PandasOnSparkBarPlot(PandasBarPlot, TopNPlotBase):
    def __init__(self, data, **kwargs) -> None: ...

class PandasOnSparkBoxPlot(PandasBoxPlot, BoxPlotBase):
    def boxplot(self, ax, bxpstats, notch: Incomplete | None = None, sym: Incomplete | None = None, vert: Incomplete | None = None, whis: Incomplete | None = None, positions: Incomplete | None = None, widths: Incomplete | None = None, patch_artist: Incomplete | None = None, bootstrap: Incomplete | None = None, usermedians: Incomplete | None = None, conf_intervals: Incomplete | None = None, meanline: Incomplete | None = None, showmeans: Incomplete | None = None, showcaps: Incomplete | None = None, showbox: Incomplete | None = None, showfliers: Incomplete | None = None, boxprops: Incomplete | None = None, labels: Incomplete | None = None, flierprops: Incomplete | None = None, medianprops: Incomplete | None = None, meanprops: Incomplete | None = None, capprops: Incomplete | None = None, whiskerprops: Incomplete | None = None, manage_ticks: Incomplete | None = None, manage_xticks: Incomplete | None = None, autorange: bool = False, zorder: Incomplete | None = None, precision: Incomplete | None = None): ...
    @staticmethod
    def rc_defaults(notch: Incomplete | None = None, vert: Incomplete | None = None, whis: Incomplete | None = None, patch_artist: Incomplete | None = None, bootstrap: Incomplete | None = None, meanline: Incomplete | None = None, showmeans: Incomplete | None = None, showcaps: Incomplete | None = None, showbox: Incomplete | None = None, showfliers: Incomplete | None = None, **kwargs): ...

class PandasOnSparkHistPlot(PandasHistPlot, HistogramPlotBase): ...

class PandasOnSparkPiePlot(PandasPiePlot, TopNPlotBase):
    def __init__(self, data, **kwargs) -> None: ...

class PandasOnSparkAreaPlot(PandasAreaPlot, SampledPlotBase):
    def __init__(self, data, **kwargs) -> None: ...

class PandasOnSparkLinePlot(PandasLinePlot, SampledPlotBase):
    def __init__(self, data, **kwargs) -> None: ...

class PandasOnSparkBarhPlot(PandasBarhPlot, TopNPlotBase):
    def __init__(self, data, **kwargs) -> None: ...

class PandasOnSparkScatterPlot(PandasScatterPlot, TopNPlotBase):
    def __init__(self, data, x, y, **kwargs) -> None: ...

class PandasOnSparkKdePlot(PandasKdePlot, KdePlotBase): ...

def plot_pandas_on_spark(data, kind, **kwargs): ...
def plot_series(data, kind: str = 'line', ax: Incomplete | None = None, figsize: Incomplete | None = None, use_index: bool = True, title: Incomplete | None = None, grid: Incomplete | None = None, legend: bool = False, style: Incomplete | None = None, logx: bool = False, logy: bool = False, loglog: bool = False, xticks: Incomplete | None = None, yticks: Incomplete | None = None, xlim: Incomplete | None = None, ylim: Incomplete | None = None, rot: Incomplete | None = None, fontsize: Incomplete | None = None, colormap: Incomplete | None = None, table: bool = False, yerr: Incomplete | None = None, xerr: Incomplete | None = None, label: Incomplete | None = None, secondary_y: bool = False, **kwds): ...
def plot_frame(data, x: Incomplete | None = None, y: Incomplete | None = None, kind: str = 'line', ax: Incomplete | None = None, subplots: bool = False, sharex: Incomplete | None = None, sharey: bool = False, layout: Incomplete | None = None, figsize: Incomplete | None = None, use_index: bool = True, title: Incomplete | None = None, grid: Incomplete | None = None, legend: bool = True, style: Incomplete | None = None, logx: bool = False, logy: bool = False, loglog: bool = False, xticks: Incomplete | None = None, yticks: Incomplete | None = None, xlim: Incomplete | None = None, ylim: Incomplete | None = None, rot: Incomplete | None = None, fontsize: Incomplete | None = None, colormap: Incomplete | None = None, table: bool = False, yerr: Incomplete | None = None, xerr: Incomplete | None = None, secondary_y: bool = False, sort_columns: bool = False, **kwds): ...
