[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "uncert"
version = "0.2.0"
authors = [
  { name="Zhang Maiyun", email="maz005@ucsd.edu" },
]
description = "Simple arithmetic and displaying of measurements and uncertainties"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy >= 1.21.0",
]

[project.urls]
Homepage = "https://github.com/myzhang1029/uncert"
Issues = "https://github.com/myzhang1029/uncert/issues"
