[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kitchenai-whisk"
dynamic = ["version"]
description = "KitchenAI Whisk - Whisk Up Your Bento Box. A tool for running kitchenai apps."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
dependencies = [
    "typer>=0.9.0",
    "rich>=13.7.0",
    "faststream[nats]>=0.4.5",
    "anyio>=3.7.1",
    "watchfiles",
    "httpx",
    "pyyaml>=6.0",
    "pydantic>=2.0.0",
    "cookiecutter>=2.5.0",
]
[tool.hatch.build.targets.wheel]
include = [
    "whisk/**",  # Include all files in the `whisk` directory
]
[project.scripts]
whisk = "whisk.__main__:app"

[tool.hatch.version]
path = "whisk/__about__.py"

[tool.hatch.envs.default]
dependencies = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.10.0",
    "pytest-xdist>=3.3.1",  # For parallel test execution with -n flag
    "pytest-rerunfailures>=12.0",  # For test retries
    "cookiecutter>=2.5.0",  # Added for CLI tests
]

[tool.pytest.ini_options]
addopts = "-v --cov=whisk --cov-report=term-missing"
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*" 