[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "biopb"
version = "0.1.2"
requires-python = ">=3.8"
authors = [ {name = "Ji Yu", email = "jyu@uchc.edu" } ]
description = "Python bindings of BioPB: open protobuf/gRPC protocols for biomedical image processing"
readme = "README.md"
license = {file = "LICENSE"}

[project.urls]
Homepage = "https://github.com/jiyuuchc/biopb"
Documentation = "https://jiyuuchc.github.io/biopb/"
