[build-system]
requires = ["scikit-build-core>=0.3.3", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "wembed"
version = "0.0.2"
authors = [
  { name = "Jean-Pierre von der Heydt", email = "heydt@kit.edu" },
  { name = "Nikolai Maas", email = "nikolai.maas@kit.edu" },
]
description="WEmbed python bindings to calculate weighted node embeddings"
readme = "README.md"
license.file = "LICENSE"
requires-python = ">=3.8"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
]

[tool.scikit-build]
cmake.verbose = true
logging.level = "INFO"
minimum-version = "build-system.requires"
wheel.license-files = ["LICENSE"]
cmake.build-type = "Release"
sdist.exclude = ["docker_build", "docker_dev", "assets", "release", "debug", "wheelhouse", ".github"]

[tool.cibuildwheel]
linux.before-all = """yum update -y && yum install -y git wget cmake python3-devel && 
wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz &&
tar -xzf eigen-3.4.0.tar.gz && 
cd eigen-3.4.0 && 
mkdir build && 
cd build && 
cmake .. && 
make install &&
cd ../.. &&
wget https://archives.boost.io/release/1.82.0/source/boost_1_82_0.tar.gz &&
tar -xzf boost_1_82_0.tar.gz &&
cp -r boost_1_82_0/boost /usr/local/include"""
