[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "deFIBrillator"
version = "0.0.5"
authors = [
  { name="Magnus Oscar Støleggen", email="mgnsoscar@gmail.com" },
]
description = "A package used to create beam paths for milling complex geometries using a focused ion beam system."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

# ✅ Add this section for dependencies
dependencies = [
    "numpy",
    "matplotlib",
    "shapely"
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"
