# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .json_value import JsonValue
import datetime as dt
from .file_model import FileModel
from .thread_message_model import ThreadMessageModel
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ThreadWithFilesAndMessagesResponse(UniversalBaseModel):
    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    The title of the thread
    """

    extra: typing.Optional[typing.Dict[str, typing.Optional[JsonValue]]] = (
        pydantic.Field(default=None)
    )
    """
    Extra metadata for the thread
    """

    id: int
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    is_archived: typing.Optional[bool] = None
    group_id: int
    files: typing.List[FileModel]
    messages: typing.List[ThreadMessageModel]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
