# Generated by Django 5.1.5 on 2025-01-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0002_remove_created_modified_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="created",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time the checklist was added to eBird",
                null=True,
                verbose_name="created",
            ),
        ),
    ]
