[build-system]
requires = [
    "pip",
    "setuptools",
    "wheel",
    "pybind11>=2.8.0",
    "libcasm-global>=2.0.5",
    "libcasm-xtal>=2.0a12",
    "libcasm-composition>=2.0a4",
    "libcasm-clexulator>=2.0a7",
    "libcasm-configuration>=2.0a8",
    "libcasm-monte>=2.0a6",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/tests/test.py"
test-skip = "*universal2:arm64"
