[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "v-agents"
version = "0.1.3"
description = "A tiny agentic AI library."
authors = [
  { name = "Xiaozhe Yao", email = "askxzyao@gmail.com" }
]
dependencies = [
  "requests",
  "pydantic",
  "loguru",
  "aiohttp",
]

[tool.setuptools.packages.find]
include = ["vagent", "vagent.*"]
