
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-29T09:23:01-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "049d8024bb988e2659613fdca67169c8c5eb3bd0",
 "version": "6.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
