[project]
name = "torch-bspline"
dynamic = ["version"]
description = "A simple library for using b-splines in pytorch."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "Hugo Melchers", email = "h.a.melchers@tue.nl"},
    { name = "Jeffrey Cochran", email = "jeffrey.david.cochran@gmail.com"},
]
keywords = ["bpsline", "b-spline", "spline", "pytorch", "torch", "spline", "interpolation", "approximation"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.9",
]
dependencies = [
    "torch~=2.5.1",
    "numpy~=1.26.4",
    "scipy~=1.13.1",
    "matplotlib"
]


[project.urls]
Homepage = "https://github.com/jeffrey-cochran/torch_bspline"
Issues = "https://github.com/jeffrey-cochran/torch_bspline/issues"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project.optional-dependencies]
test = [
    "pytest",
    "hypothesis",
    "tabulate",
    "PyQt6",
]
dev = [
    "pytest",
    "hypothesis",
    "tabulate",
    "PyQt6",
    "black",
]


[tool.hatch.version]
path = "src/torch_bspline/__about__.py"


[tool.hatch.build.targets.wheel]
packages = [
    "src/torch_bspline"
]


[tool.hatch.envs.test]
template = "default"
features = [
    "test"
]


[tool.hatch.envs.dev]
template = "default"
features = [
    "dev"
]
