[project]
name = "gluonts_customized"
version = "0.1.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy<=2.2.2",
    "orjson<=3.10.15",
    "pandas<=2.2.3",
    "pydantic<=2.10.6",
    "scikit-learn<=1.6.1",
    "toolz<=1.0.0",
    "tqdm<=4.67.1",
    "ujson<=5.10.0",
    "numba<= 0.61.0",
    "torch<=2.6.0",
    "lightning<=2.5.0.post0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "setuptools>=75.8.0",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]