from py4j.java_gateway import JavaObject as JavaObject
from pyspark import since as since
from pyspark._globals import _NoValueType

class RuntimeConfig:
    def __init__(self, jconf: JavaObject) -> None: ...
    def set(self, key: str, value: str | int | bool) -> None: ...
    def get(self, key: str, default: str | None | _NoValueType = ...) -> str | None: ...
    def unset(self, key: str) -> None: ...
    def isModifiable(self, key: str) -> bool: ...
