
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-12T16:21:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9dbbf96c4825f78af6d1b48cd471f2bba00f3fac",
 "version": "0.10.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
