[project]
name = "panel-material-ui"
channels = ["pyviz/label/dev", "conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = ">=3.10"
panel = ">=1.6.1a1"
packaging = "*"

[host-dependencies]
pip = "*"
setuptools = ">=61"
setuptools-scm = "*"
hatchling = "*"
hatch-vcs = "*"
nodejs = ">=18"
esbuild = "*"

[feature.compile.dependencies]
nodejs = ">=18"
esbuild = "*"

[feature.compile.tasks]
compile = "panel compile panel_material_ui --file-loader woff woff2"
compile-develop = "panel compile panel_material_ui --build-dir build --file-loader woff woff2 --watch"

[feature.test.dependencies]
pytest = ">=6"
pytest-cov = "*"
pytest-rerunfailures = "*"
pytest-xdist = "*"
mypy = "*"
[feature.test.tasks]
test = "pytest"
test-coverage = "pytest --cov=panel_material_ui --cov-report=xml --cov-report=term-missing"

[feature.test-ui]
channels = ["microsoft"]

[feature.test-ui.dependencies]
playwright = { version = "*", channel = "microsoft" }
pytest-playwright = { version = "*", channel = "microsoft" }
pytest-asyncio = "*"
jupyter_server = "*"
esbuild = "*"
packaging = "*"

[feature.test-ui.tasks]
_install-ui = 'playwright install chromium'

[feature.test-ui.tasks.test-ui]
cmd = 'pytest ./tests/ui --ui --browser chromium -n logical --dist loadgroup --reruns 3 --reruns-delay 10'
depends-on = ["_install-ui"]

[feature.build.dependencies]
python-build = "*"
twine = "*"
wheel = "*"
[feature.build.tasks]
build-wheel = "python -m build --no-isolation ."
check-wheel = "twine check dist/*"

[feature.lint.dependencies]
pre-commit = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[environments]
default = ["test"]
py310 = ["py310", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
test-ui = ["py312", "test", "test-ui"]
build = ["build"]
compile = ["py312", "compile"]
lint = { features = ["lint"], no-default-feature = true }
