[build-system]
requires      = ["poetry", "python_version>='3.9'"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "greennode"
version = "0.0.1"
authors = [
        "GreenNode AI <support@greennode.ai>"
]
description = "Python client for GreenNode's Cloud Platform!"
readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
]
repository = "https://github.com/greennode-ai/greennode-python"
homepage = "https://github.com/greennode-ai/greennode-python"


[tool.poetry.dependencies]
python = "^3.8"
datasets = ">=3.0.0"
tabulate = "^0.9.0"


[tool.poetry.urls]
"Homepage" = "https://github.com/greennode-ai/greennode-python"
"Bug Tracker" = "https://github.com/greennode-ai/greennode-python/issues"

[tool.poetry.scripts]
greennode = "greennode.cli.cli:main"

[tool.mypy]
strict = true
mypy_path = "."