[tool.poetry]
name = "cloud-regions-info"
version = "v1.0.1"
description = "A Python package for retrieving detailed cloud region information across AWS, Azure, GCP, and other cloud providers."
authors = ["Ditikrushna Giri <ping@ditikrushna.xyz>"]
license = "MIT"
include = ["cloud_regions_info/mappings/*.json"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pydantic = "1.10.5"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
