# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: info@navteca.com
author_name: Navteca LLC
has_binder: true
has_settings: false
kind: server
labextension_name: jupyterlab-bxplorer
project_short_description: This is a JupyterLab extension that allows users to explore
    and interact with cloud storage services.
python_name: jupyterlab_bxplorer
repository: https://github.com/Navteca/jupyterlab-bxplorer
test: true

