[project]
name = "xi-pipes"
description = "Custom pipes"
version = "0.0.8"
readme = "README.md"
authors = [
    { name = "Javier Iserte", email = "javiserte@gmail.com" }
]
dependencies = [
    "pipe",
]

[build-system]
requires = [
    "setuptools >= 40.9.0",
]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.2",
]
