
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-12T12:42:19-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b1c7655863e37b1d67b2121be05f0d2638145be",
 "version": "0.4.48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
