[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "pyscrew"
version = "0.1.4"
description = "A Python package for accessing industrial research data from a screw driving system"
authors = [
    { name = "Nikolai West", email = "nikolai.west@tu-dortmund.de" }
]
requires-python = ">=3.11"
dependencies = [
    "requests>=2.28.0",    # For downloading the respective files via Zenodo
    "tqdm>=4.65.0",        # For progress bars during downloads
    "pyyaml>=6.0.0",       # For loading scenario info
    "pydantic>=2.10.6",    # For data validation
    "scikit_learn>=1.6.1", # For data preprocessing
    "pandas>=2.2.3",       # For data handling
]
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
]
keywords = ["manufacturing", "screw driving", "industrial data", "open data", "research data"]
[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]
[project.urls]
"Homepage" = "https://github.com/nikolaiwest/pyscrew"
"Bug Tracker" = "https://github.com/nikolaiwest/pyscrew/issues"
"Documentation" = "https://github.com/nikolaiwest/pyscrew#readme"