# This file was auto-generated by Fern from our API Definition.

from .api_voice import ApiVoice
from .api_voice_gender import ApiVoiceGender
from .auth_token_response import AuthTokenResponse
from .generate_speech_response import GenerateSpeechResponse
from .pronunciation_detail import PronunciationDetail
from .pronunciation_detail_type import PronunciationDetailType
from .style_details import StyleDetails
from .word_duration import WordDuration

__all__ = [
    "ApiVoice",
    "ApiVoiceGender",
    "AuthTokenResponse",
    "GenerateSpeechResponse",
    "PronunciationDetail",
    "PronunciationDetailType",
    "StyleDetails",
    "WordDuration",
]
