# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biopb/image/detection_request.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'biopb/image/detection_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from biopb.image import image_data_pb2 as biopb_dot_image_dot_image__data__pb2
from biopb.image import detection_settings_pb2 as biopb_dot_image_dot_detection__settings__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#biopb/image/detection_request.proto\x12\x0b\x62iopb.image\x1a google/protobuf/field_mask.proto\x1a\x1c\x62iopb/image/image_data.proto\x1a$biopb/image/detection_settings.proto\"\xaa\x01\n\x10\x44\x65tectionRequest\x12*\n\nimage_data\x18\x01 \x01(\x0b\x32\x16.biopb.image.ImageData\x12:\n\x12\x64\x65tection_settings\x18\x02 \x01(\x0b\x32\x1e.biopb.image.DetectionSettings\x12.\n\nfield_mask\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.FieldMaskB\x0f\n\x0b\x62iopb.imageP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biopb.image.detection_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013biopb.imageP\001'
  _globals['_DETECTIONREQUEST']._serialized_start=155
  _globals['_DETECTIONREQUEST']._serialized_end=325
# @@protoc_insertion_point(module_scope)
