[project]
name = "cli-automation"
version = "1.0.4"
description = "Network Automation from CLI using Netmiko & Scrapli"
authors = [
    {name = "Ed Scrimaglia",email = "edgardo.scrimaglia@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10, <4.0"
dependencies = [
    "typer (>=0.15.1,<0.16.0)",
    "scrapli (>=2025.1.30,<2026.0.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "rich (>=13.9.4,<14.0.0)",
    "netmiko (==4.5.0)",
    "aiofiles (>=24.1.0,<25.0.0)"
]

[project.scripts]
cla="cli_automation.main:app"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
