[tool.poetry]
name = "exasol-udf-mock-python"
version = "0.4.0"
description = "Mocking framework for Exasol Python UDFs"

license = "MIT"

authors = [
    "Torsten Kilias <torsten.kilias@exasol.com>"
]

readme = 'README.md'

repository = "https://github.com/exasol/udf-mock-python"
homepage = "https://github.com/exasol/udf-mock-python"

keywords = ['exasol', 'udf', 'mock', 'testing']

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.3"
numpy =  ">=1.26.4,<2"

[tool.poetry.dev-dependencies]
pytest = "^8.2.2"
pytest-cov = "^5.0.0"

