import numpy as np
from _typeshed import Incomplete
from pyspark.sql.types import Row, StructType

__all__ = ['ImageSchema']

class _ImageSchema:
    def __init__(self) -> None: ...
    @property
    def imageSchema(self) -> StructType: ...
    @property
    def ocvTypes(self) -> dict[str, int]: ...
    @property
    def columnSchema(self) -> StructType: ...
    @property
    def imageFields(self) -> list[str]: ...
    @property
    def undefinedImageType(self) -> str: ...
    def toNDArray(self, image: Row) -> np.ndarray: ...
    def toImage(self, array: np.ndarray, origin: str = '') -> Row: ...

ImageSchema: Incomplete
