from numpy import ndarray
from pyspark.mllib.common import callMLlibFunc as callMLlibFunc
from pyspark.rdd import RDD as RDD
from typing import Iterable

class KernelDensity:
    def __init__(self) -> None: ...
    def setBandwidth(self, bandwidth: float) -> None: ...
    def setSample(self, sample: RDD[float]) -> None: ...
    def estimate(self, points: Iterable[float]) -> ndarray: ...
