
# This file was generated by 'versioneer.py' (0.29+8.gf9bbd1b) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-12T18:33:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "50e2d69ccfc079ea2be55c583be87806535850ad",
 "version": "0.66.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
