[project]
name = "leviticus"
version = "0.0.0.dev0"
description = "Leviticus"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    { name = "Jackmin801", email = "ongjackm@gmail.com" }
]
dependencies = [
    "fastapi[standard]",
    "uvicorn[standard]",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["leviticus"]
