[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pygments_djc"
version = "1.0.1"
requires-python = ">=3.8, <4.0"
description = "Pygments Lexers for django-components"
keywords = ["django", "components", "pygments", "lexer", "html", "js", "css"]
readme = "README.md"
authors = [
    {name = "Juro Oravec", email = "juraj.oravec.josefson@gmail.com"},
]
classifiers = [
    "Framework :: Django",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    'pygments>=2.15',
]
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/django-components/pygments-djc/"


[tool.setuptools.packages.find]
where = ["src"]
include = ["pygments_djc*"]
exclude = ["pygments_djc.tests*"]
namespaces = false

[tool.black]
line-length = 119
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | activate
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3
include_trailing_comma = "True"
known_first_party = "pygments_djc"

[tool.flake8]
ignore = ['E302', 'W503']
max-line-length = 119
exclude = [
  '__pycache__',
  'env',
  '.env',
  '.venv',
  '.tox',
  'build',
]

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
exclude = [
    'build',
]

[[tool.mypy.overrides]]
module = "pygments_djc.*"
disallow_untyped_defs = true


[tool.pytest.ini_options]
testpaths = [
    "tests"
]
