[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wiliot_certificate"
version = "1.3.0a1"
authors = [
  { name="Wiliot", email="support@wiliot.com" }
]
description = "A library for certifying Wiliot-compliant boards"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
license = { file = "LICENSE" }

dependencies = [
    "jinja2>=3.1.5",
    "appdirs>=1.4.4",
    "plotly>=6.0.0",
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "colorama>=0.4.6",
    "tabulate>=0.9.0",
    "wiliot-core>=5.9.1",
    "paho-mqtt>=2.1.0",
    "bitstruct>=8.19.0",
    "protobuf>=5.29.3",
    "wiliot-api>=4.10.8",
    "jsonschema>=4.23.0",
    "statsmodels>=0.14.4"
]

[project.urls]
Wiliot = "https://www.wiliot.com"
Certified = "https://www.wiliot.com/product/ambient-iot-network#partner-device-certification"

[project.scripts]
wlt-gw-certificate = "gw_certificate.gw_certificate_cli:main"

[tool.setuptools.package-data]
gw_certificate = ["tests/*.csv", "tests/static/*.csv", "templates/*.html"]