[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "infomaniak-ai"
dynamic = ["version"]
description = 'A python wrapper around Infomaniak AI tools'
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = []
authors = [{ name = "Gabriel Cuendet", email = "gabriel.cuendet@gmail.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["aiohttp", "aiofiles", "requests-toolbelt==1.0.0"]

[project.urls]
Documentation = "https://github.com/gcuendet/infomaniak-ai#readme"
Issues = "https://github.com/gcuendet/infomaniak-ai/issues"
Source = "https://github.com/gcuendet/infomaniak-ai"

[tool.hatch.version]
path = "src/infomaniak_ai/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = ["mypy>=1.0.0"]

[tool.hatch.envs.hatch-test]
extra-dependencies = ["pytest-asyncio", "pytest-dotenv"]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/infomaniak_ai tests}"

[tool.coverage.run]
source_pkgs = ["infomaniak_ai", "tests"]
branch = true
parallel = true
omit = ["src/infomaniak_ai/__about__.py"]

[tool.coverage.paths]
infomaniak_ai = ["src/infomaniak_ai", "*/infomaniak-ai/src/infomaniak_ai"]
tests = ["tests", "*/infomaniak-ai/tests"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
markers = """
    real_api_calls: mark tests requiring real API calls."""
