
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-12T11:34:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cdedfcf58380812f82a3b3d29d80bdebf760dd18",
 "version": "0.10.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
