image: python:3.11-bullseye

stages:
  - build
  - test

variables:
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"

cache:
  key:
    files:
      - requirements-dev.txt
      - setup.py
  paths:
    - .cache/pip/

build-job:
  stage: build
  script:
    - pip install -U pip setuptools wheel
    - pip install --no-deps -r requirements-dev.txt
    - make check
    - python -m build --sdist

  artifacts:
    paths:
      - dist/
    expire_in: 1 days

