[project]
name = "onedm"
description = "Common data model for IoT and IoT devices"
keywords = ["iot", "data model"]
authors = [
    {name = "Christian Sandberg", email = "christiansandberg@me.com"},
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries",
  "Topic :: File Formats",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]
dependencies = [
    "pydantic>=2",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/christiansandberg/onedm.git"
Issues = "https://github.com/christiansandberg/onedm/issues"

[tool.setuptools_scm]

[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pylint."messages control"]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-many-instance-attributes",
    "too-many-return-statements",
    "duplicate-code",
    "fixme",
]

[tool.pylint.format]
max-line-length = 88

[tool.mypy]
plugins = "pydantic.mypy"
