[project]
name = "{{NAME}}"
version = "0.1.0"
description = "{{DESCRIPTION}}"
authors = [{ name = "John Doe", email = "john.doe@composabl.com" }]
dependencies = [
    "composabl-core"
]

[composabl]
type = "skill-coach"
entrypoint = "{{NAME_MODULE}}.coach:Coach"
