
# This file was generated by 'versioneer.py' (0.29+8.gf9bbd1b) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-12T19:58:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "45ac3d2afe45c3c660b78faa855ff18d3a1a4239",
 "version": "0.66.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
