[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"



#python3 -m build
#python3 -m pip install --upgrade twine
#python3 -m pip install --upgrade packaging
#python3 -m twine upload --repository testpypi dist/*

#python3 -m twine upload dist/*