- version: 1.9.0
  name: container_toolkit
  url: "https://oss.mthreads.com/product-release/Cloud/mt-cloudnative-toolkits-v1.9.0/external/mt-container-toolkit-1.9.0.zip"
  md5: e6a1ccd611bee2abff7724c5430ba115
