# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .file_type import FileType
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class DealFileUploadRequest(UniversalBaseModel):
    """
    File upload request for deal-related files
    """

    file: str = pydantic.Field()
    """
    The file to upload
    """

    name: str = pydantic.Field()
    """
    Name of the file including extension
    """

    type: FileType = pydantic.Field()
    """
    Type/category of the file
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
