
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-13T13:19:37+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "00b295c950230c4f44495d7d27848677a304335a",
 "version": "1.1.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
