"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.dbu.v0.dbumodels_pb2
import ansys.api.geometry.v0.curves_pb2
import ansys.api.geometry.v0.models_pb2
import grpc

class CurvesStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        ansys.api.dbu.v0.dbumodels_pb2.EntityIdentifier,
        ansys.api.geometry.v0.models_pb2.Curve] = ...

    GetAll: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.curves_pb2.GetAllRequest,
        ansys.api.geometry.v0.curves_pb2.GetAllResponse] = ...


class CurvesServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(self,
        request: ansys.api.dbu.v0.dbumodels_pb2.EntityIdentifier,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.Curve: ...

    @abc.abstractmethod
    def GetAll(self,
        request: ansys.api.geometry.v0.curves_pb2.GetAllRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.curves_pb2.GetAllResponse: ...


def add_CurvesServicer_to_server(servicer: CurvesServicer, server: grpc.Server) -> None: ...
