[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "webdriver-hj3415"
version = "2.0.0"
authors = [{name = "Hyungjin Kim", email = "hj3415@gmail.com"}]
description = "The webdriver functions for hj3415"
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
    "selenium>=4.27.1",
    "webdriver-manager>=4.0.2",
    "utils_hj3415>=3.0.13",
]

[project.urls]
Home = "https://www.hyungjin.kr"

[tool.flit.sdist]
exclude = ["tests/", ".gitignore"]