[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "saltriverprojectenergyapi"
version = "1.0.1"
authors = [
  { name="Dave Rich", email="drich@nea-online.net" },
]
description = "Unofficial api for the Arizona Salt River Project (SRP) API"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/tehdave/SaltRiverProjectEnergyAPI"
Issues = "https://github.com/tehdave/SaltRiverProjectEnergyAPI/issues"