
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-12T10:52:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e683707a50da0e286c4d56beac97eb96a109db5",
 "version": "0.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
