[project]
name = "oneenv"
version = "0.1.0"
description = "OneEnv: Environment variable management and generation tool"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
]

[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
oneenv = "oneenv.cli:main"
