[tool.poetry]
name = "just-semantic-search-agent"
version = "0.1.2"
description = "Semantic and hybrid search agent"
authors = ["Anton Kulaga <antonkulaga@gmail.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
keywords = ["python", "llm", "science", "review", "hybrid search", "semantic search", "agent"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.11",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]

packages = [
    { include = "just_semantic_search" }
]

include = [
    "bin/*.sh",
    "bin/*.bat"
]

[tool.poetry.scripts]
index-markdown = "just_semantic_search.agent.index_markdown:app"
parse-papers = "just_semantic_search.agent.scripts:parse_papers"


[tool.poetry.dependencies]
python = ">=3.11,<3.15"
just-semantic-search-scholar = "*"
just-agents-web = ">=0.5.3"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0"]
build-backend = "poetry.core.masonry.api" 

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "pep440"


[tool.poetry.group.dev.dependencies]
just-semantic-search-meili = { path = "../meili", develop = true }
just-semantic-search-scholar = { path = "../scholar", develop = true }
just-semantic-search = { path = "../core", develop = true }
