from _typeshed import Incomplete

DEFAULT_HADOOP: str
DEFAULT_HIVE: str
SUPPORTED_HADOOP_VERSIONS: Incomplete
SUPPORTED_HIVE_VERSIONS: Incomplete
UNSUPPORTED_COMBINATIONS: Incomplete

def checked_package_name(spark_version, hadoop_version, hive_version): ...
def checked_versions(spark_version, hadoop_version, hive_version): ...
def convert_old_hadoop_version(spark_version, hadoop_version): ...
def install_spark(dest, spark_version, hadoop_version, hive_version) -> None: ...
def get_preferred_mirrors(): ...
def download_to_file(response, path, chunk_size=...) -> None: ...
