[tool.poetry]
name = "codeforge-ai"
version = "1.1"
description = ""
authors = ["Aravinda Harithsa", "Shourya Banerjee"]
readme = "README.md"

packages = [
    { include = "app" },
    { include = "scripts.py"}
]

include = [
    { path = "templates/**/*", format = ["sdist", "wheel"] },
    { path = "scripts.py", format = ["sdist", "wheel"] },
    { path = "pyproject.toml", format = ["sdist", "wheel"] }
]


[tool.poetry.dependencies]
python = ">=3.9,<4.0"
uvicorn = "^0.23.2"
pydantic = "^2.9.2"
jinja2 = "^3.1.3"
tiktoken = "^0.8.0"
boto3 = "^1.34.88"
httpx = "0.27.2"
langchain-aws = ">=0.2,<0.3"
langchain = ">=0.3,<0.4"
langgraph = ">=0.2,<0.3"
langchainhub = ">=0.1.15"
langchain-anthropic = ">=0.2,<0.3"
langchain-cli = ">=0.0.15"
pydevd-pycharm = "^243.18137.19"
langchain-community = "^0.3.1"
pytz = "2024.2"
python-multipart = "0.0.20"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
setuptools = "^68.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
codeforge-ai = 'scripts:codeforge_ai'
dev = 'scripts:dev'
finstall = "scripts:frontend_install"
fstart = "scripts:frontend_start"
fbuild = "scripts:frontend_build"
build = "scripts:build_and_archive"

[tool.poetry.build]
script = "build.py"
