[project]
name = "tecton-gen-ai"
description = "[private preview] Tecton Gen AI SDK"
authors = [{ name = "Tecton, Inc.", email = "support@tecton.ai" }]
dependencies = [
    "pandas>=2.2.1",
    "tecton-client>=0.3.0",
    "typing_extensions>=4.5",
    "langchain-core>0.3",
    "cloudpickle>=2.0.0",
    "diskcache>=5.6.3",
]
readme = "README.pypi.md"
requires-python = ">=3.9"
license = { text = "Tecton Proprietary" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: Other/Proprietary License",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://tecton.ai"
Documentation = "https://docs.tecton.ai"

[project.optional-dependencies]
realtime = ["aws-secretsmanager-caching"]
tecton = ["tecton[rift]==1.1.0", "tecton-runtime==1.1.0"]
langchain = ["langchain>0.3", "langchain-core>0.3", "langchain-community>0.3"]
openai = ["langchain-openai>=0.3.3", "langchain>0.3", "langchain-core>0.3", "langchain-community>0.3"] # TODO: remove this cap
bedrock = ["langchain-aws", "langchain>0.3", "langchain-core>0.3", "langchain-community>0.3"]
google = ["langchain-google-genai", "langchain>0.3", "langchain-core>0.3", "langchain-community>0.3"]
llama-index = ["llama-index"]
structured = ["instructor>=1.5.0"]
dev = [
    "rich",
    "markdown",
    "pygments",
    "ipywidgets",
    "diagrams",
    "tecton==1.1.0",
    "tecton-runtime==1.1.0",
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/tecton_gen_ai/_version.py"


[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.uv]
managed = true
dev-dependencies = [
    "setuptools",
    "wheel",
    "pytest",
    "pytest-cov>=5.0.0",
    "pytest-asyncio",
    "pre-commit>=3.7.1",
    "pylint>=3.2.6",
    "ruff>=0.6.3",
    "langchain-openai>=0.1.23",
    "langchain-anthropic",
    "lancedb>=0.12.0",
    "jupyterlab>=4.2.5",
]

[tool.uv.workspace]
members = ["demo/marshmallow-demo"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.coverage.run]
source = ['src/tecton_gen_ai']
omit = ['*/testing/*']

[tool.pytest.ini_options]
addopts = "-p pytest_cov -p tecton_gen_ai -vvv --cov=src --cov-report=term-missing:skip-covered"
