from inspect import Signature
from pyspark.errors import PySparkNotImplementedError as PySparkNotImplementedError
from pyspark.sql.pandas._typing import PandasGroupedAggUDFType as PandasGroupedAggUDFType, PandasScalarIterUDFType as PandasScalarIterUDFType, PandasScalarUDFType as PandasScalarUDFType
from pyspark.sql.pandas.utils import require_minimum_pandas_version as require_minimum_pandas_version
from typing import Any, Callable

def infer_eval_type(sig: Signature, type_hints: dict[str, Any]) -> PandasScalarUDFType | PandasScalarIterUDFType | PandasGroupedAggUDFType: ...
def check_tuple_annotation(annotation: Any, parameter_check_func: Callable[[Any], bool] | None = None) -> bool: ...
def check_iterator_annotation(annotation: Any, parameter_check_func: Callable[[Any], bool] | None = None) -> bool: ...
def check_union_annotation(annotation: Any, parameter_check_func: Callable[[Any], bool] | None = None) -> bool: ...
