# Project build file

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
version = '0.2.0'

name = 'heterogeneity-index'
authors = [
    {name='Clément Haëck', email='clement.haeck@locean.ipsl.fr'}
]
description = 'A library to detect fronts using an heterogeneity index'

readme = 'README.md'
requires-python = '>=3.10'
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'Topic :: Utilities'
]

dependencies = [
    'numpy>=1.24',
    'numba>=0.57'
]

[project.urls]
'Homepage' = 'https://gitlab.in2p3.fr/biofronts/heterogeneity-index'

[tool.mypy]
plugins = 'numpy.typing.mypy_plugin'
ignore_missing_imports = true
exclude = ['^doc/extensions', '^tests']

[tool.ruff]
line-length = 88
target-version = 'py310'
extend-exclude = ['doc/extensions/*.py', 'doc/conf.py', 'tests']

[tool.ruff.lint]
select = [
       'E',  # pycodestyle
       'W',  # pycodestyle
       'I',  # isort
       'N',  # pep8-name
       'B',  # bugbear
       'G',  # flake8-logging-format
       'F',  # pyflakes
       'UP',  #pyupgrade
       'D',  #pydocstyle
       'PL', # pylint
]

ignore = [
       'E226', # missing whitespace around arithmetic operator
       'D203', # one blank line before class
       'D213', # multiline docstring start at 2nd line
       'D417', # not all parameters need doc
       'PLR2004', # magic values
       'PLR0913', # too many arguments
]

unfixable = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = 'numpy'
