from _typeshed import Incomplete
from pyspark.errors import PySparkRuntimeError as PySparkRuntimeError
from pyspark.serializers import UTF8Deserializer as UTF8Deserializer, read_int as read_int, write_with_length as write_with_length

def launch_gateway(conf: Incomplete | None = None, popen_kwargs: Incomplete | None = None): ...
def local_connect_and_auth(port, auth_secret): ...
def ensure_callback_server_started(gw) -> None: ...
