[project]
name = "lighter-zoo"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=0.27.1",
    "jupyter>=1.1.1",
    "monai[itk,nibabel,skimage]>=1.4.0",
    "safetensors>=0.5.2",
    "torch>=2.5.1",
]

[tool.setuptools]
packages = ["lighter_zoo"]
