from _typeshed import Incomplete
from pyspark.errors.error_classes import ERROR_CLASSES_MAP as ERROR_CLASSES_MAP

class ErrorClassesReader:
    error_info_map: Incomplete
    def __init__(self) -> None: ...
    def get_error_message(self, error_class: str, message_parameters: dict[str, str]) -> str: ...
    def get_message_template(self, error_class: str) -> str: ...
