[project]
name = "geoloc"
version = "0.1.1"
description = "A CLI tool for geographical location utilities."
authors = [{name = "swami.padmanabhan",email = "swami.padman@gmail.com"}]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
requests = "2.32.3"
python = "3.11"
click="8.1.7"
pytest="8.3.4"
pydantic="2.10.6"
pytest-mock="3.14.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
geoloc-util = "geoloc.geoloc_util:cli"
