[project]
name = "arquee"
version = "0.4.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.0",
    "pymssql>=2.3.2",
    "pyspark>=3.5.4",
    "python-dotenv>=1.0.1",
    "sqlalchemy>=2.0.38",
    "vaex>=4.17.0",
    "waitress>=3.0.2",
]

[project.scripts]
arquee-init-server = "arquee.cli:start_server"
arquee = "arquee.cli:create_files"


[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "setuptools>=75.8.0",
    "twine>=6.1.0",
    "wheel>=0.45.1",
]
