# This file was auto-generated by Fern from our API Definition.

import typing

UserType = typing.Union[
    typing.Literal["business", "consumer", "supplier", "asset", "labor", "business_user"], typing.Any
]
