[project]
name = "hatch-pinned-extra"
dynamic = [ "version" ]
description = "Add a packaging extra with pinned dependencies from a lock file"
readme = "README.md"
authors = [
    { name = "Edgar Ramírez Mondragón", email = "edgarrm358@gmail.com" }
]
license = "MIT"
requires-python = ">=3.9"
dependencies = [
    "hatchling>=1.27.0",
    "tomli; python_version < '3.11'",
    "typing-extensions; python_version < '3.10'",
]

[project.entry-points.hatch]
pinned_extra = "hatch_pinned_extra"

[dependency-groups]
dev = [
    "pytest>=8",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.ruff]
line-length = 100
