project: shfsl
dataset: miniImageNet
dataset_path: /home/sungwon/common_dataset/miniImageNet/Ravi
save_path: /home/sungwon/ckpt
save_freq: 10
num_epoch: 500
num_workers: 8
batch_size: 256
lr: 0.03
weight_decay: 1e-04
momentum: 0.9
encoder: ResNet18
proj:
    proj_size: 512-512-128
    activate_fn: ReLU
model:
    name: SimCLR
    temperature: 0.07
device: ""
wandb_run_id: ""
group: "{name}_{encoder}_{dataset}"
exp_name: "{name}_{encoder}_{dataset}_{current_time}_{seed}_{word}"
