# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biopb/image/rpc_process_image.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'biopb/image/rpc_process_image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from biopb.image import image_data_pb2 as biopb_dot_image_dot_image__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#biopb/image/rpc_process_image.proto\x12\x0b\x62iopb.image\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1c\x62iopb/image/image_data.proto\"}\n\x0eProcessRequest\x12*\n\nimage_data\x18\x01 \x01(\x0b\x32\x16.biopb.image.ImageData\x12\x0f\n\x07op_name\x18\x02 \x01(\t\x12.\n\nfield_mask\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"Q\n\x0fProcessResponse\x12*\n\nimage_data\x18\x01 \x01(\x0b\x32\x16.biopb.image.ImageData\x12\x12\n\nannotation\x18\x02 \x01(\t\"\x18\n\x07OpNames\x12\r\n\x05names\x18\x01 \x03(\t2\x8c\x01\n\x0cProcessImage\x12@\n\x03Run\x12\x1b.biopb.image.ProcessRequest\x1a\x1c.biopb.image.ProcessResponse\x12:\n\nGetOpNames\x12\x16.google.protobuf.Empty\x1a\x14.biopb.image.OpNamesB\x0f\n\x0b\x62iopb.imageP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biopb.image.rpc_process_image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013biopb.imageP\001'
  _globals['_PROCESSREQUEST']._serialized_start=145
  _globals['_PROCESSREQUEST']._serialized_end=270
  _globals['_PROCESSRESPONSE']._serialized_start=272
  _globals['_PROCESSRESPONSE']._serialized_end=353
  _globals['_OPNAMES']._serialized_start=355
  _globals['_OPNAMES']._serialized_end=379
  _globals['_PROCESSIMAGE']._serialized_start=382
  _globals['_PROCESSIMAGE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
