FIRST_NEWARE_DATA_TABLE = 'main_first_table'
SECOND_NEWARE_DATA_TABLE = 'main_second_table'
FIRST_NEWARE_AUX_TABLE = 'aux_first_table'
SECOND_NEWARE_AUX_TABLE = 'aux_second_table'

NW_VOLTAGE = 'test_vol'
NW_CURRENT = 'test_cur'
NW_TEMP = 'test_tmp'
NW_AUX_CHANNEL = 'auxchl_id'
NW_STEP_RANGE = 'cur_step_range'
NW_TIMESTAMP = 'test_time'
NW_DATESTAMP = 'test_atime'
NW_CAP_CHG = 'test_capchg'
NW_CAP_DCHG = 'test_capdchg'
NW_ENGY_CHG = 'test_engchg'
NW_ENGY_DCHG = 'test_engdchg'

NW_SEQ = 'seq_id'
NW_IP = 'ip'
NW_DEVICE = 'dev_uid'
NW_UNIT = 'unit_id'
NW_CHANNEL = 'chl_id'
NW_TEST = 'test_id'
NW_CYCLE = 'cycle'
NW_STEP = 'step_id'
NW_STEP_TYPE = 'step_type'

NW_CACHE_CAP_CHG = 'cap_chg'
NW_CACHE_CAP_DCHG = 'cap_dchg'
NW_CACHE_ENGY_CHG = 'engy_chg'
NW_CACHE_ENGY_DCHG = 'engy_dchg'
NW_CACHE_CC_RATIO = 'cc_ratio'
NW_CACHE_CC_CAP_RATIO = 'cc_cap_ratio'
NW_CACHE_CYCLE_SEQ = 'cycle_end_seq'
NW_CACHE_OCV_DRP_CHG = 'ocv_drop_chg'
NW_CACHE_OCV_DRP_DCHG = 'ocv_drop_dchg'
NW_CACHE_V_MIN = 'v_min'
NW_CACHE_V_MAX = 'v_max'
NW_CACHE_R_CHG = 'r_chg'
NW_CACHE_R_DCHG = 'r_dchg'
NW_CACHE_DUR = 'duration'
NW_CACHE_V_REST_BEFORE_CHG = 'v_rest_before_chg'
NW_CACHE_V_REST_BEFORE_DCHG = 'v_rest_before_dchg'
NW_CACHE_UPDATE_TIME = 'update_time'
NW_CACHE_UPDATE_TIME_CC = 'update_time_cc'
NW_CACHE_UPDATE_TIME_OCV = 'update_time_ocv'
NW_CACHE_UPDATE_TIME_R = 'update_time_r'
NW_CACHE_UPDATE_TIME_T = 'update_time_t'
NW_CACHE_UPDATE_TIME_AUX_OCV = 'update_time_aux_ocv'
NW_CACHE_AUXC_OCV_DRP_CHG = 'auxc_ocv_drop_chg'
NW_CACHE_AUXC_OCV_DRP_DCHG = 'auxc_ocv_drop_dchg'
NW_CACHE_AUXA_OCV_DRP_CHG = 'auxa_ocv_drop_chg'
NW_CACHE_AUXA_OCV_DRP_DCHG = 'auxa_ocv_drop_dchg'
NW_CACHE_AUXA_MIN = 'auxa_v_min'
NW_CACHE_AUXA_MAX = 'auxa_v_max'
NW_CACHE_AUXC_MIN = 'auxc_v_min'
NW_CACHE_AUXC_MAX = 'auxc_v_max'
NW_CACHE_T1_MIN = 't1_min'
NW_CACHE_T1_MAX = 't1_max'
NW_CACHE_T2_MIN = 't2_min'
NW_CACHE_T2_MAX = 't2_max'
NW_CACHE_CURR_CHG = 'curr_chg'
NW_CACHE_CURR_DCHG = 'curr_dchg'
NW_CACHE_R_CHG_END = 'r_chg_end'
NW_CACHE_R_DCHG_END = 'r_dchg_end'
NW_CACHE_DURATION_CHG = 'duration_chg'

NW_CACHE_MERGED_COLUMNS = {
    NW_CYCLE, NW_CACHE_CAP_CHG, NW_CACHE_CAP_DCHG, NW_CACHE_ENGY_CHG, NW_CACHE_ENGY_DCHG,
    NW_CACHE_CC_RATIO, NW_CACHE_CC_CAP_RATIO, NW_CACHE_OCV_DRP_CHG, NW_CACHE_OCV_DRP_DCHG,
    NW_CACHE_V_MIN, NW_CACHE_V_MAX, NW_CACHE_R_CHG, NW_CACHE_R_DCHG, NW_CACHE_DUR,
    NW_CACHE_V_REST_BEFORE_CHG, NW_CACHE_V_REST_BEFORE_DCHG
}

NW_CACHE_COLUMNS = {
    NW_IP, NW_DEVICE, NW_UNIT, NW_CHANNEL, NW_TEST, NW_CYCLE, NW_CACHE_CYCLE_SEQ,
    NW_CACHE_CAP_CHG, NW_CACHE_CAP_DCHG, NW_CACHE_ENGY_CHG, NW_CACHE_ENGY_DCHG,
    NW_CACHE_CC_RATIO, NW_CACHE_CC_CAP_RATIO, NW_CACHE_OCV_DRP_CHG, NW_CACHE_OCV_DRP_DCHG,
    NW_CACHE_V_MIN, NW_CACHE_V_MAX, NW_CACHE_R_CHG, NW_CACHE_R_DCHG, NW_CACHE_DUR,
    NW_CACHE_UPDATE_TIME, NW_CACHE_UPDATE_TIME_CC, NW_CACHE_UPDATE_TIME_OCV,
    NW_CACHE_UPDATE_TIME_AUX_OCV, NW_CACHE_UPDATE_TIME_R, NW_CACHE_UPDATE_TIME_T, 
    NW_CACHE_AUXC_OCV_DRP_CHG, NW_CACHE_AUXC_OCV_DRP_DCHG, NW_CACHE_AUXA_OCV_DRP_CHG, 
    NW_CACHE_AUXA_OCV_DRP_DCHG, NW_CACHE_AUXC_MIN, NW_CACHE_AUXC_MAX, NW_CACHE_AUXA_MIN, 
    NW_CACHE_AUXA_MAX, NW_CACHE_T1_MIN, NW_CACHE_T1_MAX, NW_CACHE_T2_MIN, NW_CACHE_T2_MAX,
    NW_CACHE_CURR_CHG, NW_CACHE_CURR_DCHG, NW_CACHE_R_CHG_END, NW_CACHE_R_DCHG_END,
    NW_CACHE_DURATION_CHG, NW_CACHE_V_REST_BEFORE_CHG, NW_CACHE_V_REST_BEFORE_DCHG
}

NW_DATA_SIGNIFICANT_COLUMNS = {
    NW_UNIT, NW_CHANNEL, NW_TEST, NW_SEQ, NW_CYCLE, NW_STEP, NW_STEP_TYPE, 
    NW_TIMESTAMP, NW_VOLTAGE, NW_CURRENT, NW_STEP_RANGE, NW_DATESTAMP,
    NW_CAP_CHG, NW_CAP_DCHG, NW_ENGY_CHG, NW_ENGY_DCHG
}

NW_AUX_SIGNIFICANT_COLUMNS = [NW_SEQ, NW_AUX_CHANNEL, NW_TEMP]

PREV_SUFFIX = '_prev'

CACHE_CONNECTION_KWARG = 'cache'
TTL_KWARG = 'ttl'
NX_KWARG = 'nx'

OUTLIER_STD_COEFFECIENT = 3