[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cadnano2"
version = "2.4.13"
description = "Cadnano2 for PyQt6"
authors = [
    {name = "Shawn Douglas", email = "shawn.douglas@ucsf.edu"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "PyQt6",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[project.scripts]
cadnano2 = "cadnano2.main:main"

[tool.setuptools]
packages = ["cadnano2"]
package-data = {"cadnano2" = ["ui/mainwindow/images/*.svg", "ui/mainwindow/images/*.png"]}