
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-12T12:07:01-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "704514bad94c1a4e2955993b9992cd3f00d81a13",
 "version": "4.1.58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
