[project]
name = "tbxtools"
version = "0.1.0"
description = "Utilities for working with TermBase Exchange files (TBX)."
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
