[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyvtools"
description = "Python tools"
version = "1.3"
requires-python = ">= 3.13.0"
dependencies = [
  "numpy",
  "matplotlib",
  "opencv-python",
  "scikit-image",
  "pillow",
  "scikit-learn",
  "tifffile",
]
authors = [
  {name = "Valeria Pais", email = "valeriarpais@gmail.com"},
]
readme = "README.md"
license = {text = "MIT License"}
keywords = ["deep learning", "pytorch"]

classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]

[project.urls]
Repository = "https://github.com/0xInfty/PyVTools.git"
Homepage = "https://github.com/0xInfty/PyVTools"
Issues = "https://github.com/0xInfty/PyVTools/issues"