# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class ConcentrationEndpointTopUsersDetail(UniversalBaseModel):
    user_id: str = pydantic.Field()
    """
    The user identifier.
    """

    amount: float = pydantic.Field()
    """
    The amount for the user.
    """

    amount_percent: float = pydantic.Field()
    """
    The pdf of the total amount for the user.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
