# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class WeatherGauge(UniversalBaseModel):
    date: str = pydantic.Field()
    """
    The date of the data point
    """

    label: str = pydantic.Field()
    """
    The label of the weather gauge
    """

    weather_gauge: typing.Optional[float] = pydantic.Field(default=None)
    """
    The value of the combined weather gauge incorporating all stages at the given date
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
