[project]
name = "postomc"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Nicolas Linden", email = "nicolas@nlinden.com" }]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "h5py>=3.12.1",
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "pint>=0.24.4",
    "uncertainties>=3.2.2",
    "xlsxwriter>=3.2.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
pomc = "postomc.CLI.depletion:convert"
