[project]
name = "gspread-helpers"
authors = [
  {name="Michael Letts", email="lettsmt@gmail.com"},
]
maintainers = [
  {name="Michael Letts", email="lettsmt@gmail.com"},
]
requires-python = ">=3.10"
dependencies = ["attrs (>=24.3.0,<25.0.0)"]
description = "A simple Python package which provides supplementary helper methods for gspread."
readme = "README.md"
license = { text = "MIT" }
keywords = [ "gspread", "gspread-helpers", "gspread_helpers" ]
version = "0.0.24"

[project.urls]
repository = "https://github.com/michaelthomasletts/gspread-helpers"
documentation = "https://michaelthomasletts.github.io/gspread-helpers/index.html"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
black = "^24.10.0"
isort = "^5.13.2"
flake8 = "^7.1.1"
pre-commit = "^4.0.1"
sphinx = "^8.1.3"
numpydoc = "^1.8.0"
pydata-sphinx-theme = "^0.16.1"

[tool.pytest.ini_options]
markers = ["exceptions", "functions", "imports"]

[tool.black]
line-length = 79
target-version = ["py310"]
verbose = true

[tool.isort]
line_length = 79
ensure_newline_before_comments = true
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3