
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-12T22:17:45-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c3ee1fd1f65cdb99d02edcca614a242c88377cd",
 "version": "3.2.2.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
