[tool.poetry]
name = "belfry_magicbell"
version = "2.3.4"
description = "Fork of the unofficial Python SDK for MagicBell"
authors = ["Alex Tulenko <alex@belfrysoftware.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/BelfrySoftware/magicbell-python-sdk"
keywords = ["magicbell", "sdk"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^2.6"
httpx = ">=0.28.1"
orjson = "^3.7.6"
pydantic-settings = "^2.0.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-randomly = "^3.12.0"
black = "^22.3.2"
isort = "^5.10.1"
flake8 = "^5.0.4"
nox = "^2022.8.7"
nox-poetry = "^1.0.0"
bump2version = "^1.0.1"
pytest-xdist = "^2.5.0"
starlette = ">=0.20.4,<0.27.0"
pytest-asyncio = "^0.19.0"
flake8-docstrings = "^1.6.0"
bump-pydantic = "^0.7.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.3.1"
mkdocs-material = "^8.3.9"
mkdocs-jupyter = "^0.21.0"
mkdocstrings = "^0.19.0"
mkdocstrings-python = "^0.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100

[tool.coverage.run]
branch = false
omit = ["belfry_magicbell/_version.py", "*/tests/*"]

[tool.coverage.report]
exclude_lines = ["if self.debug:",
                 "pragma: no cover",
                 "raise AssertionError",
                 "raise NotImplementedError",
                 "if __name__ == '__main__':"]
ignore_errors = true
omit = ["belfry_magicbell/_version.py"]
