[project]
name = "xi_covutils"
requires-python = ">=3.9"
version = "0.7.0.6"
dependencies = [
  "biopython >=1.80",
  "requests >=2.28.1",
  "click >=8.1.3",
  "matplotlib >=3.6.3",
  "Python-Deprecated >=1.1.0",
  "pandas >=1.5.3",
  "typing_extensions >=4.4.0",
  "pipe>=2.2",
]
description = "Tools to work with protein covariation"
authors = [{ name = "Javier Iserte", email = "jiserte@leloir.org.ar" } ]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.2.0",
  "mock>=4.0.4",
  "pylint>=2.15.5",
  "pdoc3>=0.10.0",
  "Python-Deprecated>=1.1.0",
  "radon>=5.1.0"
]

[project.urls]
Repository = "https://gitlab.com/bioinformatics-fil/xi_covutils"

[tool.setuptools]
include-package-data = true
packages = [
  "xi_covutils",
  "xi_covutils.blast",
  "xi_covutils.matrices",
  "xi_covutils.msa",
  "xi_covutils.primers",
  "xi_covutils.seqs",
  "xi_covutils.plotting"
]

[project.scripts]
xi_covutils = "xi_covutils.xi_covutils_app:cli"

[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[tool.maturin]
module-name = "xi_covutils.rs_covutils"

[tool.pyright]
reportMissingModuleSource="none"
