
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-12T08:20:57+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa39534b965fd1be3e80557eaf4c50a45ec43a67",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
