
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-07T16:31:15+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "29315c3af23a34ed5e5746757ace8dc6a45d8883",
 "version": "1.1.0b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
