[project]
name = "marshmallow-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["tecton-gen-ai"]

[tool.uv.sources]
tecton-gen-ai = { workspace = true }
