# Generated by Django 5.1.5 on 2025-01-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklist",
            name="created",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="location",
            name="created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="created",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="observer",
            name="created",
        ),
        migrations.RemoveField(
            model_name="observer",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="species",
            name="created",
        ),
        migrations.RemoveField(
            model_name="species",
            name="modified",
        ),
    ]
