# Generated by Django 5.1.5 on 2025-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0003_add_checklist_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data describing a Checklist.",
                verbose_name="Data",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data describing a Location",
                verbose_name="Data",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data describing an Observation.",
                verbose_name="Data",
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data describing an Observer.",
                verbose_name="Data",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data describing a Species.",
                verbose_name="Data",
            ),
        ),
    ]
