[project]
name = "codo-python"
version = "1.0.4"
description = "(C)ompute (O)perations in (D)ependency (O)rder"
readme = "README.md"
dependencies = []

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
