
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-13T09:10:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "089731c686893e68e423480b87db5d2606b8aad8",
 "version": "0.1.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
