[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pygoodpractices"
version = "0.1.0"
description = "A tool to set up pre-commit hooks automatically"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    { name = "petudeveloper" }
]
keywords = ["pre-commit", "automation", "best practices"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "pre-commit",
    "virtualenv>=20.0.0"
]
requires-python = ">=3.7"

[project.scripts]
pygood-init = "pygoodpractices.initializer:initialize_pygoodpractices"
pygood = "pygoodpractices.precommit_runner:main"