# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .company_response import CompanyResponse
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ListCompaniesResponse(UniversalBaseModel):
    total_count: int
    page: int
    page_size: int
    data: typing.List[CompanyResponse]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
