# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .column_mini_metadata import ColumnMiniMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ModelMetadata(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    The name of the model.
    """

    description: str = pydantic.Field()
    """
    A plain-english description of the model and what it represents.
    """

    columns: typing.List[ColumnMiniMetadata] = pydantic.Field()
    """
    The columns used in the model.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
