# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .user_with_permissions_response import UserWithPermissionsResponse
from .group_response import GroupResponse
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class UserRoleResponse(UniversalBaseModel):
    user: UserWithPermissionsResponse
    group: GroupResponse

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
