# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/terraquantum/credits/v1alpha1/credits_service.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'com/terraquantum/credits/v1alpha1/credits_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.terraquantum.credits.v1alpha1 import get_balance_pb2 as com_dot_terraquantum_dot_credits_dot_v1alpha1_dot_get__balance__pb2
from com.terraquantum.credits.v1alpha1 import subscribe_pb2 as com_dot_terraquantum_dot_credits_dot_v1alpha1_dot_subscribe__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7com/terraquantum/credits/v1alpha1/credits_service.proto\x12!com.terraquantum.credits.v1alpha1\x1a\x33\x63om/terraquantum/credits/v1alpha1/get_balance.proto\x1a\x31\x63om/terraquantum/credits/v1alpha1/subscribe.proto\"\x8b\x01\n\x16\x43heckPermissionRequest\x12\x1f\n\x0bobject_type\x18\x01 \x01(\tR\nobjectType\x12\x1a\n\x08relation\x18\x02 \x01(\tR\x08relation\x12\x17\n\x07user_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n\tobject_id\x18\x04 \x01(\tR\x08objectId\"@\n\x17\x43heckPermissionResponse\x12%\n\x0ehas_permission\x18\x01 \x01(\x08R\rhasPermission2\x8e\x03\n\x0e\x43reditsService\x12y\n\nGetBalance\x12\x34.com.terraquantum.credits.v1alpha1.GetBalanceRequest\x1a\x35.com.terraquantum.credits.v1alpha1.GetBalanceResponse\x12\x88\x01\n\x0f\x43heckPermission\x12\x39.com.terraquantum.credits.v1alpha1.CheckPermissionRequest\x1a:.com.terraquantum.credits.v1alpha1.CheckPermissionResponse\x12v\n\tSubscribe\x12\x33.com.terraquantum.credits.v1alpha1.SubscribeRequest\x1a\x34.com.terraquantum.credits.v1alpha1.SubscribeResponseB\xba\x02\n%com.com.terraquantum.credits.v1alpha1B\x13\x43reditsServiceProtoP\x01ZUterraquantum.swiss/tq42_grpc_client/com/terraquantum/credits/v1alpha1;creditsv1alpha1\xa2\x02\x03\x43TC\xaa\x02!Com.Terraquantum.Credits.V1alpha1\xca\x02!Com\\Terraquantum\\Credits\\V1alpha1\xe2\x02-Com\\Terraquantum\\Credits\\V1alpha1\\GPBMetadata\xea\x02$Com::Terraquantum::Credits::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.credits.v1alpha1.credits_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.com.terraquantum.credits.v1alpha1B\023CreditsServiceProtoP\001ZUterraquantum.swiss/tq42_grpc_client/com/terraquantum/credits/v1alpha1;creditsv1alpha1\242\002\003CTC\252\002!Com.Terraquantum.Credits.V1alpha1\312\002!Com\\Terraquantum\\Credits\\V1alpha1\342\002-Com\\Terraquantum\\Credits\\V1alpha1\\GPBMetadata\352\002$Com::Terraquantum::Credits::V1alpha1'
  _globals['_CHECKPERMISSIONREQUEST']._serialized_start=199
  _globals['_CHECKPERMISSIONREQUEST']._serialized_end=338
  _globals['_CHECKPERMISSIONRESPONSE']._serialized_start=340
  _globals['_CHECKPERMISSIONRESPONSE']._serialized_end=404
  _globals['_CREDITSSERVICE']._serialized_start=407
  _globals['_CREDITSSERVICE']._serialized_end=805
# @@protoc_insertion_point(module_scope)
