[project]
name = "Flyre"
version = "1.0.1"
description = "A pixel art shooter with a skill tree.(DLC version)"
authors = [
  { name="ddorn", email="diego.dorn@free.fr" },
  { name="mark4d4", email="sevcow4674@gmail.com" },
]
license = "MIT"
[tool.hatch.dependencies]
python = "^3.8"
pyinstaller = "^4.2"
pygame = "^2.0.1"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["src","flyre.pyw","readme.md"]