[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "argvparse"
authors = [{ name = "CodeCrafter-TL", email = "1825456084@qq.com" }]
maintainers = [{ name = "CodeCrafter-TL", email = "1825456084@qq.com" }]
description = "Argv parser for Python."
readme = "README.md"
license = { text = "MIT License" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Intended Audience :: Developers",
    "Typing :: Typed",
]
dynamic = ["version"]

[project.urls]
"Bug tracker" = "https://github.com/CodeCrafter-TL/argvparse/issues"
"Source code" = "https://github.com/CodeCrafter-TL/argvparse"

[tool.setuptools.dynamic]
version = { attr = "argvparse.__version__" }

[tool.setuptools.packages.find]
include = ["argvparse*"]
