[tool.poetry]
name = "leveelogic"
version = "0.9.1"
description = ""
authors = ["Rob van Putten <breinbaasnl@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pydantic = ">=1.10.7"
simplejson = "^3.19.2"
pytest = "^8.2.2"
pandas = "^2.2.2"
matplotlib = "^3.8.3"
pyproj = "^3.6.1"
requests = "^2.32.3"
xmltodict = "^0.13.0"
haversine = "^2.8.1"
pyshp = "^2.3.1"
netcdf4 = "^1.7.2"
shapely = "^2.0.6"
python-dotenv = "^1.0.1"
pydantic-settings = "^2.7.1"
pydantic-extra-types = "^2.10.2"
jinja2 = "^3.1.5"
d-geolib = "^2.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
