[project]
name = "funtable"
version = "1.0.23"
description = "funtable"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "fundrive>=1.2.18", "funutil>=1.0.5",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []
