[project]
name = "hst_funcs"
version = "0.0.10"
authors = [
  { name="HST", email="ye0077@naver.com" },
]
description = "My package for practicing to deploy on PyPI."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

