name: NATS Server Code Coverage
on:
  workflow_dispatch: {}

  schedule:
    - cron: "40 4 * * *"

jobs:
  nightly_coverage:
    runs-on: ubuntu-latest

    env:
      GOPATH: /home/runner/work/nats-server
      GO111MODULE: "on"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src/github.com/nats-io/nats-server

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Run code coverage
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          set -e
          cd src/github.com/nats-io/nats-server
          ./scripts/cov.sh upload
          set +e

      - name: Convert coverage.out to coverage.lcov
        # Use commit hash here to avoid a re-tagging attack, as this is a third-party action
        # Commit 69ef3d59a24cc6e062516a73d8be123e85b15cc0 = tag v1.1.0
        uses: jandelgado/gcov2lcov-action@69ef3d59a24cc6e062516a73d8be123e85b15cc0
        with:
          infile: acc.out
          working-directory: src/github.com/nats-io/nats-server

      - name: Coveralls
        # Use commit hash here to avoid a re-tagging attack, as this is a third-party action
        # Commit 3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 = tag v2
        uses: coverallsapp/github-action@643bc377ffa44ace6394b2b5d0d3950076de9f63
        with:
          github-token: ${{ secrets.github_token }}
          file: src/github.com/nats-io/nats-server/coverage.lcov
