[build-system]
requires = [
  "setuptools>=61.0",
  "robotframework>=7.0"]
build-backend = "setuptools.build_meta"

[project]
name = "robotframework-dependencysolver"
dynamic = ["version"]
dependencies = [
  "robotframework>=7.0",
  "robotframework-dependencylibrary>=4.0",
]
requires-python = ">=3.10"
authors = [
  { name="Joonas Kuisma", email="kuisma.joonas@gmail.com" },
]
description="A Robot Framework prerunmodifier for interdependent test cases execution."
readme = "README.md"
license = {file = "LICENSE"}

keywords = ["Robot Framework", "DependencySolver", "prerunmodifier"]
classifiers = [
    #"Development Status :: 5 - Production/Stable",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Testing",
    "Framework :: Robot Framework :: Library",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "robotframework-pabot>=4.1",
]
pabot = [
    "robotframework-pabot>=4.1",
]

[project.scripts]
depsol = "DependencySolver.run:main"

[project.urls]
Homepage = "https://github.com/joonaskuisma/robotframework-dependencysolver"
Issues = "https://github.com/joonaskuisma/robotframework-dependencysolver/issues"

[tool.setuptools.dynamic]
version = {attr = "DependencySolver._version.__version__"}
