[tool.poetry]
name = "blprint"
version = "0.1.0"
description = "A simple scaffolding cli"
authors = ["Mateus Gurgel <mateusgurgel15@gmail.com>"]
readme = "README.md"
packages = [{include = "modules", from = "src\\blprint"}]

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.15.1"
jinja2 = "^3.1.5"

[tool.poetry.scripts]
bp = 'src.blprint.main:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
